from django.urls import path
from . import views

app_name = 'freelance_marketplace'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_user, name='login'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('logout/', views.logout_user, name='logout_user'),
    path('admin-logout/', views.admin_logout, name='admin_logout'),
    path('about/', views.about_page, name='about_page'),
    path('mission/', views.mission_page, name='mission_page'),
    path('how-it-works/', views.how_it_works_page, name='how_it_works_page'),
    path('contact/', views.contact_page, name='contact_page'),
    path('post-project/', views.post_project, name='post_project'),
    path('login-choice/', views.login_choice, name='login_choice'),
    path('select-login/', views.select_login, name='select_login'),
    path('admin-login/', views.admin_login, name='admin_login'),
    path('login/customer/', views.customer_login, name='customer_login'),
    path('login/freelancer/', views.freelancer_login, name='freelancer_login'),
    path('register/freelancer/', views.freelancer_register, name='freelancer_register'),
    path('register/customer/', views.customer_register, name='customer_register'),
    path('register/', views.register_choice, name='register_choice'),
    path('dashboard/', views.dashboard_redirect, name='dashboard_redirect'),
    path('freelancer-dashboard/', views.freelancer_dashboard, name='freelancer_dashboard'),
    path('customer-dashboard/', views.customer_dashboard, name='customer_dashboard'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-panel/freelancers/', views.admin_freelancers, name='admin_freelancers'),
    path('admin-panel/customers/', views.admin_customers, name='admin_customers'),
    path('admin-panel/gigs/', views.admin_gigs, name='admin_gigs'),
    path('admin-panel/orders/', views.admin_orders, name='admin_orders'),
    path('admin-panel/reviews/', views.admin_reviews, name='admin_reviews'),
    path('gigs/', views.all_gigs, name='all_gigs'),
    path('gigs/add/', views.add_gig, name='add_gig'),
    path('gigs/my/', views.my_gigs, name='my_gigs'),
    path('gig/<int:gig_id>/', views.gig_detail, name='gig_detail'),
    path('gigs/', views.gigs_list, name='gigs'),
    path('gig/edit/<int:gig_id>/', views.edit_gig, name='edit_gig'),
    path('gig/delete/<int:gig_id>/', views.delete_gig, name='delete_gig'),
    path('order-gig/<int:gig_id>/', views.order_gig, name='order_gig'),
    path('order/<int:order_id>/', views.order_detail, name='order_detail'),
    path('order/<int:order_id>/review/', views.add_review, name='add_review'),
    path('freelancer-gigs/', views.freelancer_dashboard, name='freelancer_gigs'),
    path('freelancers/', views.all_freelancers, name='all_freelancers'),
    path('freelancer-pending-orders/', views.freelancer_pending_orders, name='freelancer_pending_orders'),
    path('freelancer-completed-orders/', views.freelancer_completed_orders, name='freelancer_completed_orders'),
    path('freelancer/order/<int:order_id>/', views.freelancer_order_detail, name='freelancer_order_detail'),
    path('freelancer/orders/', views.freelancer_orders, name='freelancer_orders'),
    path('freelancer/orders/update/<int:order_id>/<str:new_status>/', views.update_order_status, name='update_order_status'),
    path('confirm-order/<int:order_id>/', views.confirm_order, name='confirm_order'),
    path('chat/<int:order_id>/', views.chat_view, name='chat_view'),  
    path('admin/orders/', views.admin_orders, name='admin_orders'),
    path('admin/orders/delete/<int:order_id>/', views.admin_delete_order, name='admin_delete_order'),
    path('admin/revenue/', views.revenue_summary, name='revenue_summary'),
    path('category/<slug:category_slug>/', views.category_gigs, name='category_gigs'),
    path('category/<slug:slug>/', views.category_page, name='category_page'),

]
