# Generated by Django 5.2.7 on 2025-11-17 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_pending',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='gig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance_marketplace.gig'),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
