# Generated by Django 5.2.7 on 2025-11-17 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_marketplace', '0002_remove_order_is_pending_remove_order_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='order',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
